### ISSUE TITLE
Server crash on new players

### ISSUE THREAD

**Issue by thorbaert** [JoshuaBaert/mc-node-wrapper#51]
I feel this is because of our xp autostore message trying to get info on a player that doesn't exists yet

**Comment by thorbaert** [comment]
LOG
```TypeError: Cannot read property 'xpAutoStore' of null
    at Player.findOne (C:\code\personal\mc-node-wrapper\app\data\index.js:167:32)
    at C:\code\personal\mc-node-wrapper\node_modules\mongoose\lib\model.js:4599:16
    at C:\code\personal\mc-node-wrapper\node_modules\mongoose\lib\query.js:4351:12
    at model.Query.Query._completeOne (C:\code\personal\mc-node-wrapper\node_modules\mongoose\lib\query.js:2054:12)
    at Immediate.Query.base.findOne.call (C:\code\personal\mc-node-wrapper\node_modules\mongoose\lib\query.js:2116:10)
    at Immediate.<anonymous> (C:\code\personal\mc-node-wrapper\node_modules\mquery\lib\utils.js:116:16)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at C:\code\personal\mc-node-wrapper\node_modules\mongoose\lib\model.js:4601:13
    at C:\code\personal\mc-node-wrapper\node_modules\mongoose\lib\query.js:4351:12
    [... lines matching original stack trace ...]
    at processImmediate (timers.js:658:5)
```
